### ISSUE TITLE
Tab key has no effect on Mac

### ISSUE THREAD

**Issue by jorisw** [AlvaroBrey/adb-uninstall#1]
Great app. Saves a lot of time going through the apps interactively.

Unfortunately the Tab key won't do anything on Mac. The Enter key works however, as do the arrow keys.

**Comment by alvarobrey** [comment]
Hi @jorisw ,

This looks like a problem with `fzf` rather than this script in particular. Does <kbd>TAB</kbd> work in `fzf` at all for you?

You can test this by simply running `fzf --multi` and seeing if <kbd>TAB</kbd> selects elements.

**Comment by jorisw** [comment]
If I install fzf using Homebrew, Tab works in selecting items.

```
~ ▲ fzf --version
0.18.0 (brew)
```

Installing fzf using Homebrew had no effect on adb-install however.

**Comment by alvarobrey** [comment]
Just so we're clear: <kbd>tab</kbd> works on `fzf --multi` but not on `adb-uninstall`, right? I'll take a look to see what can be the issue.

**Comment by alvarobrey** [comment]
Also, is any error printed out at all?

**Comment by jorisw** [comment]
Correct, tab to select, works on `fzf --multi` (installed separately using Homebrew) but not in `adb-uninstall`. 

No errors, it just means I can only uninstall one app at a time.

**Comment by jorisw** [comment]
I'm using the native Terminal on macOS 10.14.6.

**Comment by alvarobrey** [comment]
Can you do another test? Sorry to bother you, but I don't have a macOS computer with which to try.

I'd like you to try:

`FOO=$(fzf --multi)`

To see if the subshell (`$()`)  is what's causing the issues.

**Comment by jorisw** [comment]
Works too.

FWIW, I had to convert your test.sh to LF line endings from CRLF, or the path to bash would yield a `/bin/bash\r: No such file or directory`.

**Comment by alvarobrey** [comment]
Sorry about that, I created the script while on Windows and didn't notice.

In any case, now I'm oficially 100% out of ideas. Sorry :(

**Comment by jorisw** [comment]
No problem. Let me know if I can test anything else.

**Comment by AlvaroBrey** [comment]
Tested successfully today in MacOS Ventura today with no other problems than https://github.com/AlvaroBrey/adb-uninstall/commit/a763ef6a0625e9d44d58882af101d10c8c94fde8. Considering this solved.
